# Generated by Django 5.2.1 on 2025-06-25 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_employee_manager'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Работники'},
        ),
        migrations.AlterField(
            model_name='employee',
            name='employment_date',
            field=models.DateField(verbose_name='Дата приёма на работу'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(max_length=100, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='total_paid',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
    ]
