# Generated by Django 5.2.1 on 2025-06-25 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_alter_employee_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='level',
            field=models.PositiveIntegerField(verbose_name='Уровень'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.employee', verbose_name='Начальник'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='salary',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Зарплата'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='total_paid',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='Общая сумма выплат'),
        ),
    ]
