# Generated by Django 5.2.1 on 2025-06-25 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_alter_employee_level_alter_employee_manager_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Работники', 'verbose_name_plural': 'Работники'},
        ),
        migrations.AlterField(
            model_name='employee',
            name='total_paid',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=15, verbose_name='Общая сумма выплат'),
        ),
    ]
